### ISSUE TITLE
Pouvoir donner des précisions sur une activité

### ISSUE THREAD

**Issue by BrunoJunior** [BrunoJunior/bdzkermesse#84]
Pour la gestion des activités, pouvoir ajouter les fonctionnalités suivantes : 

1. Ajouter une description à destination des bénévoles. Cette description devra pouvoir être visualisée dans le planning via un icône « point d'interrogation » qui affiche la description au survole. Dans la vue mobile, la description sera dans la boîte d'affichage de l'action en italique à côté d'un icône « point d'interrogation ».
2. Pouvoir ordonner les actions les unes aux autres sans avoir recours à l'utilisation de nombres dans le libellé
3. Ne pas afficher les actions sans créneau dans le planning
4. Pouvoir préciser qu'une activité n'est utilisée que pour de l'affichage dans le planning (exemple : les horaires de passage des spectacles).

**Comment by Julianstouch** [comment]
Commentaires sur les points proposés :
1. Un vrai plus, les bénévoles pourraient mieux comprendre à quoi ils s'inscrivent. Ex des activités que nous proposons : "Cadeau Pong" et "Triangolo" ... une description rapide de l'activité serait très utile
2. Ok, toujours profitable. Surtout utile avec le 4.
3. Très utile, pour ajouter par exemple une activité "vente des tickets de Tombola" qui est vraiment lié à ce jour, mais qui ne nécessite pas de créneau planning
4. Utile également.

Propositions supplémentaires : 
- En plus de la description, ajouter un champ "Règles du jeu" optionel pour expliquer succinctement comme faire participer les gens.
- Ajouter un type d'activité : jeux à lot immédiat , jeux à meilleur score, tirage au sort, vente direct, animation (maquillage, poney), surveillange (chateau gonfable) , autre ... visible sur le point d'interrogation avec la description

**Comment by BrunoJunior** [comment]
Pour les types d'activités, je prévois une liste figée ou chaque établissement peut créer sa propre liste de types ?
Ou une fusion des deux ?
Une partie fixe définie par le code et une autre partie en BDD pour chaque établissement...

**Comment by Julianstouch** [comment]
Une fusion des 2 serait le mieux. La liste par défaut devrait suffire, mais pourquoi pas avoir la possibilité d'ajouter quelques autres types. Vu qu'il ne s'agit que d'information "visuel" à destination des bénévoles qui s'inscrivent, il n'y a pas de conséquence à avoir libre écriture.

**Comment by BrunoJunior** [comment]
@Julianstouch Plus qu’à rajouter le bloc « Règle du jeu »
Le reste a été fait sur la branche. Ça sera prêt pour l’année prochaine lol

**Comment by BrunoJunior** [comment]
@Julianstouch Popopooo ! J’ai fait tous les points ;)

**Comment by BrunoJunior** [comment]
@Julianstouch Pour pouvoir faire des tests :
https://kermesse.preprod.web-project.fr/login
J’ai récupéré les données de prod dans une BDD à part donc pas de risque de péter les données.
