### ISSUE TITLE
Action - Nombre de ticket

### ISSUE THREAD

**Issue by Julianstouch** [BrunoJunior/bdzkermesse#95]
Dans l'écran des actions, il y a une colonne "Nombre de ticket", qui est toujours à 0.

Mais celui ci n'est pas saisissable, ni à la création ni à l'édition.
Il semblerait que ce champ soit réservé / utilisé par les Activités

![Capture d’écran du 2023-06-08 09-43-06](https://github.com/BrunoJunior/bdzkermesse/assets/8057653/5d34e1a5-9c2a-4450-bff8-3b79da66c56f)

**Comment by BrunoJunior** [comment]
@Julianstouch Corrigé et livrée sur la pré-prod …
https://kermesse.preprod.web-project.fr
