### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by Julianstouch** [BrunoJunior/bdzkermesse#97]
Il n'y a pas d'information sur ce que fait la validation du planning avant de cliquer, mais ce n'est pas trop génant.
Par contre :
- un planning validé peut-être revalidé , et donc une 2ème serie d'e-mails part. La validation ne fige pas le planning, les bénévoles peuvent toujours s'y inscrire. Je suggère de renommer le bouton "Valider le planning" en "E-mailer tous les bénévoles de leurs créneaux".

- Il y a une typo dans le message de confirmation :
`Les bénévoles des créneaux complets ont été prévenus apr email !`
`Les bénévoles des créneaux complets ont été prévenus **par e-mail**`

**Comment by BrunoJunior** [comment]
FIXED
Livré sur la prod via la branche 1.2-fixes
